const Doc =[
    {
        id:"wog",
        head:"Wog",
        para:"Web Originator is a application that helps creating webpage with drag and drop and  pre-built templates .The Enrich editor comes with built in help components that makes is easy for user and also save time.user can style the components according to his taste and align the content as he wants",
        img:"",
    },
    {
        id:"pages",
        head:"Pages",
        // para:"Create Page After Registering and login the user can create the page by clicking on the create by drag and drop.On create page user should enter tha name of the page he wants to create and Clicks on save changes the page will be createduser can see te pages create by him on profile-webpag",
        img:"",
    },
    {
        id:"editpages",
        head:"",
        subhead:"Edit Pages",
        para:"in order to edit the content of the page click on the edit icon from the action in the profile or on the editor page ",
        img:"/support/create.jpg",
    },
    {
        id:"createpages",
        head:"",
        subhead:"Create Pages",
        para:"Create Page After Registering and login the user can create the page by clicking on the create by drag and drop.On create page user should enter tha name of the page he wants to create and Clicks on save changes the page will be createduser can see te pages create by him on profile-webpag ",
        img:"/support/create.jpg",
    },
    {
        id:"deletePages",
        head:"",
        subhead:"Delete Pages",
        para:"Pages can  be deleted from the profile from editor also .user can go to the profile from the top bar after login clicking on the name a dropdown apears and click on the profile to check you personal data and all the pages",
        img:"",
    },
    {
        id:"renamepages",
        head:"",
        subhead:"Rename Pages",
        para:"Name of the pages only be renamed form the profile user can go to the profile from the top bar after login clicking on the name a dropdown apears and click on the profile to check you personal data and all the pages.In th e front of the page name click on pencil icon and add new name of page",
        img:"",
    },
    {
        id:"template",
        head:"Templates",
        para:"User can create webpage from the pre-built in templates.it can save time of the user.the templates are modifiable and you can do what ever you wants and make them according to your taste",
        img:"",
    },
    {
        id:"preview",
        head:"",
        subhead:"Preview Templates",
        para:" Before using any of the template user can easily see the template how its look so the user easily finds the template without wasting much time.user can navigate to template page by clicking on create button and then by template on top barClick on the preview icon on the template tab to see preview of the template",
        img:"",
    },
    {
        id:"usetemplate",
        head:"",
        subhead:"Use Templates",
        para:"After Preview if the user likes the template he will use it according to its needs .In order to use the template click on the use template button on the template page user can navigate to template page by clicking on create button and then by template on top bar",
        img:"",
    },
    {
        id:"download",
        head:"",
        subhead:"Download Templates",
        para:"User can download the template after using it by clicking on the icon of plane or save from the editor page use will gets the zip file of the code for further usage",
        img:"",
    },
    {
        id:"editor",
        head:"Editor",
        para:"By using WOG EDITOR user can create the webpage how he needs there are built in block or component which user can drag and drop in the editor to use them moreover user can style them any way he wants he can also link things or upload things ",
        img:"",
    },
    {
        id:"modileview",
        head:"",
        subhead:"Mobile/PC view",
        para:" While designing a webpage user can see how its page will look like on the different devices e.g: in order to see how its look like on the mobile click on the mobile icon on the top bar to see its view",
        img:"",
    },
    {
        id:"undoredo",
        head:"",
        subhead:"Undo/Redo",
        para:"you can undo or redo any move you do on the editor by clicking on the undo and redo you can return to the previous state of the editor in ordr to remove mistakes",
        img:"",
    },
    {
        id:"save",
        head:"",
        subhead:"Save",
        para:"After creating the webpage you must want to store the work you have done in order to that user click on the save button on the top of editor a pop up will apears which confirm your work been saved",
        img:"",
    },
    {
        id:"delete",
        head:"",
        subhead:"Delete",
        para:"The DELETE or trash button on the top of the bar will remove everything on the editor and will clear the cavas so be carefull to use this button",
        img:"",
    },
    {
        id:"previeweditor",
        head:"",
        subhead:"Preview",
        para:"this is same as looking on the different devices it will unselect the all the components and let user to take a look at his work cleanly",
        img:"",
    },
    {
        id:"tab",
        head:"Tabs",
        para:"The tabs are located under the add page menu on the editor thes are toggle able user can toggle between them .there are total of 4 tabs in that bar 1)Blocks :user can add these blocks on the editor 2) Style: it includes all type of styling 3)Layers :it use to see the nested element of the page 4)Traits : this tab is used for linking things ",
        img:"",
    },
    {
        id:"blocks",
        head:"",
        subhead:"BLOCKS",
        para:"In the editor there is a block tab on the most left of the side nav under the add page button .user can add these blocks by drag and drop on the editor these blocks are customizable user can chage color,border,font,etc  there are many blocks eg:Columns ,image,video,text etc, these are the building blocks of the editor ",
        img:"",
    },
    {
        id:"style",
        head:"",
        subhead:"Style",
        para:"This tab is used for styling the blocks present on the website all type of styling can be applied user first select the element on the editor he wants to style after that he can style as he wants eg:setting the width,height,color,background-color and many more",
        img:"",
    },
    {
        id:"layer",
        head:"",
        subhead:"Layers",
        para:"On Layers tab all the nesting of the element are visible to the user.this tab show which element are on which level on the canvas",
        img:"",
    },
    {
        id:"traits",
        head:"",
        subhead:"Traits",
        para:"This tab show all the functionality of the selected block eg:on using the link this tab will show the href tab which you can use to add the link of either the online website or existing page on the editor",
        img:"",
    },
    // {
    //     id:"",
    //     head:"",
    //     subhead:"",
    //     para:"",
    //     img:"",
    // },

]
export default Doc